add_executable(fastllm-tests test_runtime.cpp)
target_link_libraries(fastllm-tests PRIVATE fastllm)
target_include_directories(fastllm-tests PRIVATE ${CMAKE_SOURCE_DIR}/src)
add_executable(fastllm-quant-tests test_quants.cpp)
target_link_libraries(fastllm-quant-tests PRIVATE fastllm)
target_include_directories(fastllm-quant-tests PRIVATE ${CMAKE_SOURCE_DIR}/src)
add_executable(fastllm-decode-tests test_decode_ops.cpp)
target_link_libraries(fastllm-decode-tests PRIVATE fastllm)
target_include_directories(fastllm-decode-tests PRIVATE ${CMAKE_SOURCE_DIR}/src)
add_executable(fastllm-spec-tests test_spec.cpp)
target_link_libraries(fastllm-spec-tests PRIVATE fastllm)
target_include_directories(fastllm-spec-tests PRIVATE ${CMAKE_SOURCE_DIR}/src)
add_executable(fastllm-headcert-tests test_head_cert.cpp)
target_link_libraries(fastllm-headcert-tests PRIVATE fastllm)

add_executable(fastllm-shadow-tests test_shadow.cpp)
target_link_libraries(fastllm-shadow-tests PRIVATE fastllm)
